"use client";

import { useEffect, useRef, useState } from "react";
import { BarChart3, Share2 } from "lucide-react";
import { supabase } from "@/lib/supabase/client";
import PageHeader from "@/components/ui/PageHeader";
import GlassCard from "@/components/ui/GlassCard";
import { SkeletonCard } from "@/components/ui/Skeleton";
import ErrorBoundary from "@/components/ui/ErrorBoundary";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type ReportPoint = { date: string; calories: number; target: number; weight: number };
type DailyLogRow = { date: string; calories_consumed: number | null; protein_g: number | null; weight_kg: number | null };
type CardioRow = { duration_mins: number | null };

export default function ReportsPage() {
  const [loading, setLoading] = useState(true);
  const [points, setPoints] = useState<ReportPoint[]>([]);
  const [summary, setSummary] = useState({ workouts: 0, cardio: 0, protein: 0, calories: 0, weightChange: 0, topBadge: "-" });
  const reportRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const load = async () => {
      const { data: auth } = await supabase.auth.getUser();
      const userId = auth.user?.id;
      if (!userId) {
        setLoading(false);
        return;
      }

      const today = new Date();
      const start = new Date();
      start.setDate(today.getDate() - 6);

      const [logs, workouts, cardio, achievements] = await Promise.all([
        supabase.from("daily_logs").select("date, calories_consumed, protein_g, weight_kg").eq("user_id", userId).gte("date", start.toISOString().split("T")[0]).order("date", { ascending: true }),
        supabase.from("workout_sessions").select("id", { count: "exact", head: true }).eq("user_id", userId).gte("date", start.toISOString().split("T")[0]),
        supabase.from("cardio_logs").select("duration_mins").eq("user_id", userId).gte("date", start.toISOString().split("T")[0]),
        supabase.from("achievements").select("badge_id, earned_at").eq("user_id", userId).gte("earned_at", start.toISOString()),
      ]);

      const mapped = (logs.data ?? []).map((log: DailyLogRow) => ({
        date: new Date(log.date).toLocaleDateString("en-US", { weekday: "short" }),
        calories: Number(log.calories_consumed ?? 0),
        target: 1800,
        weight: Number(log.weight_kg ?? 0),
      }));

      setPoints(mapped);
      const calories = mapped.reduce((sum: number, item: ReportPoint) => sum + item.calories, 0);
      const protein = (logs.data ?? []).reduce((sum: number, log: DailyLogRow) => sum + Number(log.protein_g ?? 0), 0);
      const cardioMinutes = (cardio.data ?? []).reduce((sum: number, row: CardioRow) => sum + Number(row.duration_mins ?? 0), 0);
      const weightChange = mapped.length > 1 ? mapped[mapped.length - 1].weight - mapped[0].weight : 0;

      setSummary({
        workouts: workouts.count ?? 0,
        cardio: cardioMinutes,
        protein,
        calories: mapped.length ? Math.round(calories / mapped.length) : 0,
        weightChange: Math.round(weightChange * 10) / 10,
        topBadge: achievements.data?.[0]?.badge_id ?? "-",
      });

      setLoading(false);
    };

    void load();
  }, []);

  const breadcrumbs = [{ label: "Dashboard" }, { label: "Reports" }];

  const share = async () => {
    await navigator.clipboard.writeText(
      `📊 FitCore Weekly Report | Week of ${new Date().toLocaleDateString()}\n🔥 Streak: - days | 💪 Workouts: ${summary.workouts}/-\n🥩 Avg Protein: ${Math.round(summary.protein / 7)}g | ⚡ Calories: ${summary.calories} kcal avg\nGenerated by FitCore`
    );
  };

  const exportPdf = async () => {
    if (!reportRef.current) return;
    const [{ default: html2canvas }, { jsPDF }] = await Promise.all([import("html2canvas"), import("jspdf")]);
    const canvas = await html2canvas(reportRef.current, { scale: 2, backgroundColor: "#0A0A0F" });
    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const image = canvas.toDataURL("image/png");
    pdf.addImage(image, "PNG", 10, 10, 190, 0);
    pdf.save(`FitCore_Week_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  if (loading) return <SkeletonCard className="h-[480px] w-full" />;

  return (
    <ErrorBoundary>
      <div ref={reportRef} className="flex flex-col gap-6">
        <PageHeader title="Weekly Report" subtitle="A compact weekly snapshot of your training and nutrition." breadcrumbs={breadcrumbs} />
        <GlassCard>
          <div className="flex items-center justify-between gap-3 border-b border-white/10 pb-4">
            <div>
              <div className="text-xs uppercase tracking-[0.3em] text-white/40">Week overview</div>
              <h2 className="mt-2 text-2xl font-bold text-white">Week of your latest 7 days</h2>
            </div>
            <div className="flex gap-2">
              <button onClick={share} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/80"><Share2 className="h-4 w-4" /> Share</button>
              <button onClick={() => void exportPdf()} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-neonPurple to-neonCyan px-4 py-3 text-sm font-semibold text-black"><BarChart3 className="h-4 w-4" /> Export PDF</button>
            </div>
          </div>

          <div className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-6">
            {[
              ["Avg calories", summary.calories],
              ["Avg protein", `${Math.round(summary.protein / 7)}g`],
              ["Workouts", summary.workouts],
              ["Cardio mins", summary.cardio],
              ["Weight change", `${summary.weightChange >= 0 ? "+" : ""}${summary.weightChange} kg`],
              ["Top badge", summary.topBadge],
            ].map(([label, value]) => (
              <GlassCard key={String(label)} className="p-4"><div className="text-xs uppercase tracking-[0.3em] text-white/40">{label}</div><div className="mt-2 text-xl font-bold text-white">{String(value)}</div></GlassCard>
            ))}
          </div>

          <div className="mt-6 grid gap-6 xl:grid-cols-2">
            <GlassCard className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={points}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.08)" /><XAxis dataKey="date" stroke="#fff" /><YAxis stroke="#fff" /><Tooltip /><Bar dataKey="calories" fill="#6C63FF" /></BarChart>
              </ResponsiveContainer>
            </GlassCard>
            <GlassCard className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={points}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.08)" /><XAxis dataKey="date" stroke="#fff" /><YAxis stroke="#fff" /><Tooltip /><Line type="monotone" dataKey="weight" stroke="#00D4FF" /></LineChart>
              </ResponsiveContainer>
            </GlassCard>
          </div>
        </GlassCard>
      </div>
    </ErrorBoundary>
  );
}